name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build-windows-x86:
    name: Windows 32-bit
    runs-on: windows-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install 32-bit Python (Windows x86) using PowerShell (Python 3.9)
      - name: Install 32-bit Python (Windows x86) using PowerShell
        run: |
          # Download Python 3.9 version using Invoke-WebRequest (PowerShell's native method)
          Invoke-WebRequest -Uri https://www.python.org/ftp/python/3.9.12/python-3.9.12-embed-win32.zip -OutFile python-3.9.12-embed-win32.zip
          
          # Check if the file exists and its size
          ls -lh python-3.9.12-embed-win32.zip
          
          # Unzip the downloaded file
          Expand-Archive -Path python-3.9.12-embed-win32.zip -DestinationPath $env:ProgramFiles\Python39
          
          # Add the Python directory to PATH
          setx PATH "$env:ProgramFiles\Python39;$env:PATH"
          
      # Step 3: Install dependencies (Windows x86)
      - name: Install dependencies (Windows x86)
        run: |
          python -m pip install --upgrade pip
          # Install pyinstaller and pillow using the correct python
          python -m pip install pyinstaller pillow

      # Step 4: Build with PyInstaller (Windows x86)
      - name: Build with PyInstaller (Windows x86)
        run: |
          # --onefile: Create a single executable
          # --noconsole: Hide console window (for GUI app)
          # --icon: Specify the icon file
          python -m PyInstaller --onefile --noconsole --icon=qy.ico Auto24hStream3.3.py

      # Step 5: Upload artifact (Windows x86)
      - name: Upload artifact (Windows x86)
        uses: actions/upload-artifact@v4
        with:
          name: win-x86
          path: dist/Auto24hStream3.3.exe
