build-windows-x86:
  name: Windows 32-bit
  runs-on: windows-latest
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download and Set up Python 3.10 (x86)
      run: |
        # Download the 32-bit standalone Python distribution
        curl -LO https://github.com/indygreg/python-build-standalone/releases/download/20240401/cpython-3.10.12+20240401-i686-pc-windows-msvc-shared-install_only.tar.zst
        # Install Zstandard tool to extract .zst files
        choco install zstandard
        # Extract the .tar.zst file using zstd and tar
        zstd -d cpython-3.10.12+20240401-i686-pc-windows-msvc-shared-install_only.tar.zst -o python.tar
        tar -xvf python.tar -C python310_32

    - name: Set up Python 32-bit environment
      run: |
        # Add the extracted Python directory to PATH
        echo "$PWD/python310_32/Scripts" >> $GITHUB_PATH
        echo "$PWD/python310_32" >> $GITHUB_PATH

    - name: Install dependencies (Windows x86)
      run: |
        # Ensure pip is updated using the correct python
        python -m pip install --upgrade pip
        # Install pyinstaller and pillow using the correct python
        python -m pip install pyinstaller pillow

    - name: Build with PyInstaller (Windows x86)
      run: |
        # --onefile: Create a single executable
        # --noconsole: Hide console window (for GUI app)
        # --icon: Specify the icon file
        python -m PyInstaller --onefile --noconsole --icon=qy.ico Auto24hStream3.3.py

    - name: Upload artifact (Windows x86)
      uses: actions/upload-artifact@v4
      with:
        name: win-x86
        path: dist/Auto24hStream3.3.exe
