name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build-windows-x86:
    name: Windows 32-bit
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and install Python 3.9.13 (x86)
        run: |
          Invoke-WebRequest -Uri https://www.python.org/ftp/python/3.9.13/python-3.9.13.exe -OutFile python-installer.exe
          Start-Process -FilePath python-installer.exe -ArgumentList '/quiet InstallAllUsers=1 PrependPath=1 Include_test=0 TargetDir="C:\Python39"' -Wait
          echo "C:\Python39" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Check Python & pip
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          pip install pyinstaller pillow

      - name: Build executable
        run: |
          pyinstaller --onefile --noconsole --icon=qy.ico Auto24hStream3.3.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: win-x86
          path: dist/Auto24hStream3.3.exe
