name: Cross-platform Build

on:
  push:
    branches:
      - main
  workflow_dispatch: # 允许手动触发

jobs:
  build-windows-x64:
    name: Windows 64-bit
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10 (x64)
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow

      - name: Build with PyInstaller (Windows x64)
        run: |
          pyinstaller --onefile --noconsole --icon=qy.ico Auto24hStream3.3.py

      - name: Upload artifact (Windows x64)
        uses: actions/upload-artifact@v4
        with:
          name: win-x64
          path: dist/Auto24hStream3.3.exe

  build-windows-x86:
    name: Windows 32-bit
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and Set up Python 3.10 (x86)
        run: |
          curl -LO https://github.com/indygreg/python-build-standalone/releases/download/20240401/cpython-3.10.12+20240401-i686-pc-windows-msvc-shared-install_only.tar.zst
          mkdir python310_32
          7z x *.zst -so | tar x -C python310_32 --strip-components=1
          echo "$PWD/python310_32/Scripts" >> $GITHUB_PATH
          echo "$PWD/python310_32" >> $GITHUB_PATH

      - name: Install dependencies (Windows x86)
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller pillow

      - name: Build with PyInstaller (Windows x86)
        run: |
          python -m PyInstaller --onefile --noconsole --icon=qy.ico Auto24hStream3.3.py

      - name: Upload artifact (Windows x86)
        uses: actions/upload-artifact@v4
        with:
          name: win-x86
          path: dist/Auto24hStream3.3.exe

  build-linux:
    name: Linux x64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10 (x64)
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow

      - name: Build with PyInstaller (Linux x64)
        run: |
          pyinstaller --onefile --icon=qy.ico Auto24hStream3.3.py

      - name: Upload artifact (Linux x64)
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: dist/Auto24hStream3.3

  build-macos:
    name: macOS (x64/arm64 universal)
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow

      - name: Build with PyInstaller (macOS .app)
        run: |
          pyinstaller --windowed --onefile --icon=qy.icns Auto24hStream3.3.py

      - name: Upload artifact (macOS .app)
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: dist/Auto24hStream3.3.app

  create-release:
    name: Create GitHub Release
    needs: [build-windows-x64, build-windows-x86, build-linux, build-macos]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List downloaded artifacts (for debugging)
        run: ls -R artifacts

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
