name: Python Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # macOS 环境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'  # 根据你的需求修改Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyinstaller pillow  # 安装PyInstaller和Pillow
        python -m pip install -r requirements.txt  # 如果有额外依赖，确保从requirements.txt安装

    - name: Copy icon for macOS
      run: |
        cp qy.icns /Users/runner/work/AutoVideoStream/AutoVideoStream/  # 复制图标到项目目录

    - name: Create PyInstaller spec file for macOS
      run: |
        cat <<EOF > Auto24hStream3.3.spec
a = Analysis(
    ['Auto24hStream3.3.py'],
    pathex=['/Users/runner/work/AutoVideoStream/AutoVideoStream'],
    binaries=[],
    datas=[('/Users/runner/work/AutoVideoStream/AutoVideoStream/qy.icns', '.')],  # 添加图标文件到打包数据
    hiddenimports=[],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

app = BUNDLE(
    a,
    name='Auto24hStream3.3',
    icon='/Users/runner/work/AutoVideoStream/AutoVideoStream/qy.icns',  # 使用qy.icns作为icon
    bundle_identifier=None,
)
EOF

    - name: Build for macOS
      run: |
        pyinstaller Auto24hStream3.3.spec  # 创建MacOS可执行文件

    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/Auto24hStream3.3.app.zip  # 上传Mac可执行文件，注意修改路径
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
