name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build-windows-x86:
    name: Windows 32-bit
    runs-on: windows-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install 32-bit Python (Windows x86) using PowerShell (Python 3.9)
      - name: Install 32-bit Python (Windows x86)
        run: |
          # Download Python 3.9 embed package
          Invoke-WebRequest -Uri https://www.python.org/ftp/python/3.9.12/python-3.9.12-embed-win32.zip -OutFile python39.zip

          # Check file info
          Get-Item python39.zip

          # Unzip to folder
          Expand-Archive -Path python39.zip -DestinationPath python39

          # Add extracted folder to PATH
          echo "$PWD\python39" >> $env:GITHUB_PATH

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          ./python39/python.exe -m ensurepip
          ./python39/python.exe -m pip install --upgrade pip
          ./python39/python.exe -m pip install pyinstaller pillow

      # Step 4: Build with PyInstaller
      - name: Build executable
        run: |
          ./python39/python.exe -m PyInstaller --onefile --noconsole --icon=qy.ico Auto24hStream3.3.py

      # Step 5: Upload build artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: win-x86
          path: dist/Auto24hStream3.3.exe
