name: Cross-platform Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    name: Windows 64-bit
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          pip install pyinstaller
          pyinstaller --onefile --noconsole --icon=qy.ico Auto24hStream3.3.py
      - uses: actions/upload-artifact@v3
        with:
          name: win-x64
          path: dist/Auto24hStream3.3.exe

  build-linux:
    name: Linux x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          pip install pyinstaller
          pyinstaller --onefile --icon=qy.ico Auto24hStream3.3.py
      - uses: actions/upload-artifact@v3
        with:
          name: linux-x64
          path: dist/Auto24hStream3.3

  build-macos:
    name: macOS (x64/arm64 universal)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          pip install pyinstaller
          pyinstaller --windowed --onefile --icon=qy.ico Auto24hStream3.3.py
      - uses: actions/upload-artifact@v3
        with:
          name: macos-universal
          path: dist/Auto24hStream3.3.app
